name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-essential
      run:  sudo apt-get install build-essential
    - name: cmake -install
      run:  sudo apt-get install cmake
    - name: gtest
      run:  sudo apt-get install libgtest-dev && sudo apt-get install cmake && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo cp *.a/usr/lib
    - name: make run
      run:  make -C Lbrary/
      
      
